### ISSUE TITLE
e2e Still not working

### ISSUE THREAD

**Issue by moplin** [moplin/musicSearch-test#1]
Please fix it

```
/home/moplin/WebstormProjects/musicSearch/node_modules/selenium-webdriver/lib/atoms/error.js:108
  var template = new Error(this.message);
                 ^
UnknownError: Connection refused (Connection refused)
    at new bot.Error (/home/moplin/WebstormProjects/musicSearch/node_modules/selenium-webdriver/lib/atoms/error.js:108:18)
    at Object.bot.response.checkResponse (/home/moplin/WebstormProjects/musicSearch/node_modules/selenium-webdriver/lib/atoms/response.js:109:9)
    at /home/moplin/WebstormProjects/musicSearch/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:160:24
    at [object Object].promise.Promise.goog.defineClass.invokeCallback_ (/home/moplin/WebstormProjects/musicSearch/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1337:14)
    at [object Object].promise.ControlFlow.goog.defineClass.goog.defineClass.abort_.error.executeNext_.execute_ (/home/moplin/WebstormProjects/musicSearch/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2776:14)
    at [object Object].promise.ControlFlow.goog.defineClass.goog.defineClass.abort_.error.executeNext_ (/home/moplin/WebstormProjects/musicSearch/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2758:21)
    at goog.async.run.processWorkQueue (/home/moplin/WebstormProjects/musicSearch/node_modules/selenium-webdriver/lib/goog/async/run.js:124:15)
    at process._tickCallback (node.js:368:9)
From: Task: WebDriver.createSession()
    at Function.webdriver.WebDriver.acquireSession_ (/home/moplin/WebstormProjects/musicSearch/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:157:22)
    at Function.webdriver.WebDriver.createSession (/home/moplin/WebstormProjects/musicSearch/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:131:30)
    at [object Object].Builder.build (/home/moplin/WebstormProjects/musicSearch/node_modules/selenium-webdriver/builder.js:445:22)
    at [object Object].DriverProvider.getNewDriver (/home/moplin/WebstormProjects/musicSearch/node_modules/protractor/lib/driverProviders/driverProvider.js:38:7)
    at [object Object].Runner.createBrowser (/home/moplin/WebstormProjects/musicSearch/node_modules/protractor/lib/runner.js:186:37)
    at /home/moplin/WebstormProjects/musicSearch/node_modules/protractor/lib/runner.js:276:21
    at _fulfilled (/home/moplin/WebstormProjects/musicSearch/node_modules/q/q.js:797:54)
    at self.promiseDispatch.done (/home/moplin/WebstormProjects/musicSearch/node_modules/q/q.js:826:30)
    at Promise.promise.promiseDispatch (/home/moplin/WebstormProjects/musicSearch/node_modules/q/q.js:759:13)
    at /home/moplin/WebstormProjects/musicSearch/node_modules/q/q.js:573:44
[launcher] Process exited with error code 1

/home/moplin/WebstormProjects/musicSearch/gulp/e2e-tests.js:24
      throw err;
      ^
Error: protractor exited with code 1
```

**Comment by moplin** [comment]
Ok, its working, it was the version on NODE for some weird reason so I am setting it to node 6.10.2 LTS
